export type Scraper={id:string;name:string;url:string;collector:string;status:'Healthy'|'Broken'|'Stale'|'Healing';lastRun:string;lastHeal:string;rows:number;description:string}
export const scrapers:Scraper[]=[
{id:'products',name:'Product Price Watcher',url:'https://shop.example/products',collector:'c_prod_8f2a91',status:'Healthy',lastRun:'2 min ago',lastHeal:'Yesterday',rows:1842,description:'Capture product title, current price, rating and availability from listing pages.'},
{id:'jobs',name:'Remote Jobs Index',url:'https://jobs.example/search',collector:'c_jobs_4c81d2',status:'Broken',lastRun:'18 min ago',lastHeal:'Never',rows:0,description:'Extract job title, company, location and salary from public search results.'},
{id:'news',name:'Tech News Monitor',url:'https://news.example/latest',collector:'c_news_91aa30',status:'Healing',lastRun:'31 min ago',lastHeal:'Today 14:08',rows:492,description:'Track headline, publisher, timestamp and article URL from the latest feed.'},
{id:'flights',name:'Flight Fare Tracker',url:'https://travel.example/flights',collector:'c_fly_77bd11',status:'Stale',lastRun:'3 hr ago',lastHeal:'Aug 15',rows:76,description:'Monitor public flight cards and capture route, fare and cabin information.'},
{id:'realestate',name:'Property Snapshot',url:'https://homes.example/search',collector:'c_home_22ac81',status:'Healthy',lastRun:'6 min ago',lastHeal:'Aug 12',rows:918,description:'Capture listing title, price, beds, baths and location from public property cards.'}]
export const runs=[['Product Price Watcher','Healthy','1,842','2 min ago'],['Remote Jobs Index','Broken','0','18 min ago'],['Tech News Monitor','Healing','492','31 min ago'],['Flight Fare Tracker','Stale','76','3 hr ago'],['Property Snapshot','Healthy','918','6 min ago']]
export const heals=[['Tech News Monitor','Selector drift detected','492 rows recovered','Today 14:08'],['Product Price Watcher','Price node moved','1,842 rows verified','Yesterday 22:41'],['Property Snapshot','DOM structure changed','918 rows recovered','Aug 12']]
export const output=[{product:'Aero Runner',price:129,availability:'in_stock',rating:4.8},{product:'Cloud Hoodie',price:89,availability:'in_stock',rating:4.6},{product:'Trail Pack',price:149,availability:'low_stock',rating:4.7}]
export const rowData=[{day:'Mon',rows:820},{day:'Tue',rows:1120},{day:'Wed',rows:980},{day:'Thu',rows:1560},{day:'Fri',rows:1320},{day:'Sat',rows:1842},{day:'Sun',rows:2010}]
